package edu.gatech.cs2340.spacetraderredux.Model;

public enum Resource {

    NO_SPECIAL_RESOURCES, MINERAL_RICH, MINERAL_POOR, DESERT, LOTS_OF_WATER, RICH_SOIL, POOR_SOIL, RICH_FAUNA, LIFELESS, WEIRD_MUSHROOMS, LOTS_OF_HERBS, ARTISTIC, WARLIKE;
}
