package edu.gatech.cs2340.spacetraderredux.domain.entities

import edu.gatech.cs2340.spacetraderredux.domain.entities.enums.Resource
import edu.gatech.cs2340.spacetraderredux.domain.entities.enums.SpecialEvent
import edu.gatech.cs2340.spacetraderredux.domain.entities.enums.TechLevel


enum class Tradeable(val displayName:String, val minProduceLevel: TechLevel,
                     val minUseLevel: TechLevel, val topProductionLevel: TechLevel,
                     val baseLevelPrice: Int, val incPerLevel: Int, val percentVariance: Int,
                     val demandEvent: SpecialEvent, val cheapResource: Resource,
                     val expensiveResource: Resource, val minMerchantPrice: Int,
                     val maxMerchantPrice: Int) {

    WATER(
            "Water",
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.MEDIEVAL,
            30,
            3,
            4,
            SpecialEvent.DROUGHT,
            Resource.LOTS_OF_WATER,
            Resource.DESERT,
            30,
            50
    ),
    FURS(
            "Furs",
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.PRE_AGRICULTURAL,
            250,
            10,
            10,
            SpecialEvent.FROST,
            Resource.RICH_FAUNA,
            Resource.LIFELESS,
            230,
            280
    ),
    FOOD(
            "Food",
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.AGRICULTURE,
            100,
            5,
            5,
            SpecialEvent.FAMINE,
            Resource.RICH_SOIL,
            Resource.POOR_SOIL,
            90,
            160
    ),
    ORE(
            "Ore",
            TechLevel.MEDIEVAL,
            TechLevel.MEDIEVAL,
            TechLevel.RENAISSANCE,
            350,
            20,
            10,
            SpecialEvent.WAR,
            Resource.MINERAL_RICH,
            Resource.MINERAL_POOR,
            350,
            420
    ),
    GAMES(
            "Games",
            TechLevel.RENAISSANCE,
            TechLevel.AGRICULTURE,
            TechLevel.POST_INDUSTRIAL,
            250,
            -10,
            5,
            SpecialEvent.BOREDOM,
            Resource.ARTISTIC,
            Resource.DUMMY_RESOURCE,
            160,
            280
    ),
    FIREARMS(
            "Firearms",
            TechLevel.RENAISSANCE,
            TechLevel.AGRICULTURE,
            TechLevel.INDUSTRIAL,
            1250,
            -75,
            100,
            SpecialEvent.WAR,
            Resource.WARLIKE,
            Resource.DUMMY_RESOURCE,
            600,
            1100
    ),
    MEDICINE(
            "Medicine",
            TechLevel.EARLY_INDUSTRIAL,
            TechLevel.AGRICULTURE,
            TechLevel.POST_INDUSTRIAL,
            650,
            -20,
            10,
            SpecialEvent.PLAGUE,
            Resource.LOTS_OF_HERBS,
            Resource.DUMMY_RESOURCE,
            400,
            700
    ),
    MACHINES(
            "Machines",
            TechLevel.EARLY_INDUSTRIAL,
            TechLevel.RENAISSANCE,
            TechLevel.INDUSTRIAL,
            900,
            -30,
            5,
            SpecialEvent.WORKER_SHORTAGE,
            Resource.DUMMY_RESOURCE,
            Resource.DUMMY_RESOURCE,
            600,
            800
    ),
    NARCOTICS(
            "Narcotics",
            TechLevel.INDUSTRIAL,
            TechLevel.PRE_AGRICULTURAL,
            TechLevel.INDUSTRIAL,
            3500,
            -125,
            150,
            SpecialEvent.BOREDOM,
            Resource.WEIRD_MUSHROOMS,
            Resource.DUMMY_RESOURCE,
            2000,
            3000
    ),
    ROBOTS(
            "Robots",
            TechLevel.POST_INDUSTRIAL,
            TechLevel.EARLY_INDUSTRIAL,
            TechLevel.HI_TECH,
            5000,
            -150,
            100,
            SpecialEvent.WORKER_SHORTAGE,
            Resource.DUMMY_RESOURCE,
            Resource.DUMMY_RESOURCE,
            3500,
            5000
    )
}